name: 'Draft Release'
description: 'リリース用のPRを自動作成します。package.jsonのバージョンをバンプし、リリースノートを自動生成してドラフトPRを作成します。'
author: 'yukukotani'

branding:
  icon: 'git-pull-request'
  color: 'blue'

inputs:
  version:
    description: 'バージョンタイプ (patch, minor, major)'
    required: true
  node-version:
    description: '使用するNode.jsのバージョン'
    required: false
    default: 'lts/*'
  package-manager:
    description: 'パッケージマネージャー (npm または none)'
    required: false
    default: 'npm'
  pr-labels:
    description: 'PRに付与するラベル (カンマ区切り)'
    required: false
    default: 'Type: Release'
  draft-pr:
    description: 'PRをドラフトとして作成するか'
    required: false
    default: 'true'
  github-token:
    description: 'GitHub Token (PRとリリースノート生成に使用)'
    required: false
    default: ${{ github.token }}

outputs:
  version:
    description: 'バンプ後の新しいバージョン番号'
    value: ${{ steps.version.outputs.version }}
  pr-number:
    description: '作成されたPRの番号'
    value: ${{ steps.create-pr.outputs.pull-request-number }}
  pr-url:
    description: '作成されたPRのURL'
    value: ${{ steps.create-pr.outputs.pull-request-url }}

runs:
  using: 'composite'
  steps:
    - name: Configure Git
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Setup Node.js
      if: inputs.package-manager != 'none'
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: ${{ inputs.node-version }}

    - name: Version bump
      id: version
      shell: bash
      run: |
        if [ "$PACKAGE_MANAGER" = "npm" ]; then
          npm version "$VERSION_TYPE" --no-git-tag-version
        elif [ "$PACKAGE_MANAGER" = "none" ]; then
          echo "Package manager is set to 'none', skipping version bump"
          echo "version=unknown" >> $GITHUB_OUTPUT
          exit 0
        else
          echo "Package manager '$PACKAGE_MANAGER' is not supported for version bump"
          exit 1
        fi
        VERSION=$(jq -r '.version' package.json)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
      env:
        VERSION_TYPE: ${{ inputs.version }}
        PACKAGE_MANAGER: ${{ inputs.package-manager }}

    - name: Get release notes
      id: release-notes
      shell: bash
      run: |
        # Get the default branch
        DEFAULT_BRANCH=$(gh api "repos/$GITHUB_REPOSITORY" --jq '.default_branch')

        # Get the latest release tag using GitHub API
        if LAST_TAG=$(gh api "repos/$GITHUB_REPOSITORY/releases/latest" --jq '.tag_name' 2>/dev/null); then
          echo "Previous release found: $LAST_TAG"
        else
          LAST_TAG=""
          echo "No previous releases found - this will be the first release"
        fi

        # Generate release notes
        echo "Generating release notes for tag: v$VERSION"
        if [ -n "$LAST_TAG" ]; then
          echo "Using previous tag: $LAST_TAG"
          RELEASE_NOTES=$(gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            "/repos/$GITHUB_REPOSITORY/releases/generate-notes" \
            -f "tag_name=v$VERSION" \
            -f "target_commitish=$DEFAULT_BRANCH" \
            -f "previous_tag_name=$LAST_TAG" \
            --jq '.body')
        else
          echo "Generating notes from all commits"
          RELEASE_NOTES=$(gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            "/repos/$GITHUB_REPOSITORY/releases/generate-notes" \
            -f "tag_name=v$VERSION" \
            -f "target_commitish=$DEFAULT_BRANCH" \
            --jq '.body')
        fi

        # Set release notes as environment variable
        echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
        echo "$RELEASE_NOTES" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        VERSION: ${{ steps.version.outputs.version }}
        GITHUB_REPOSITORY: ${{ github.repository }}

    - name: Create Pull Request
      id: create-pr
      uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
      with:
        token: ${{ inputs.github-token }}
        branch: release/v${{ steps.version.outputs.version }}
        delete-branch: true
        title: "Release v${{ steps.version.outputs.version }}"
        body: |
          ${{ env.RELEASE_NOTES }}
        commit-message: "chore: release v${{ steps.version.outputs.version }}"
        labels: ${{ inputs.pr-labels }}
        assignees: ${{ github.actor }}
        draft: ${{ inputs.draft-pr }}
